### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by TTcoinDeveloper** [go-faast/faast-web#132]
![image](https://user-images.githubusercontent.com/29513200/62133328-f96c6a00-b2b4-11e9-8eec-02851c784b2c.png)

**Comment by dwolfgram** [comment]
hi @TTcoinDeveloper,

Can you post a screenshot of any errors you may have had when starting up the project? We have seen some people have trouble when compiling into production mode and are currently looking into it, in the meantime you can compile into dev mode which is completely the same as prod:

1) make sure you're on the develop branch
2) in a terminal run `npm run dev`

You can also join our support slack where it will be easier to get in touch with us:
https://join.slack.com/t/faast-team/shared_invite/enQtNjk5NDc1Nzg3NDQzLTA0NGVlZmQxMTQ0ODY0NDg1NDU3MGM0ZGRmYjg2NDdjMjgwMDEzNzAyNTU1N2JkZWFhYjQzZWI0ODRiODEyNjI

thanks!
